### ISSUE TITLE
Create pyQt Application

### ISSUE THREAD

**Issue by Lime-Parallelogram** [Lime-Parallelogram/cj2022-stately-satyrs#1]
Create basic window for our pyQT application. The first implementation of the window should have the following

- [ ] Menu bar

**Comment by maxyodedara5** [comment]
Created a basic pyQt GUI Application 

Done

- Added basic GUI
- Added Menu bar 
- Added Actions for File menu - New, Open, Save, Exit
- Added Actions for Edit menu - Copy, Paste, Cut
- Added Actions for Help menu - Help, About

TODO

- Add functionality for created actions 
- Add Microphone button for recording
